apiVersion: v1
kind: PersistentVolume
metadata: 
  name: redis-pv
  labels:
    app: ex8-kubsexercise
    type: pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  
  hostPath:
    path: /mnt/redis/data        